image: ralfjung/opam-ci:opam2

stages:
  - build

.template: &template
  stage: build
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  except:
  - triggers
  - schedules
  - api

## Build jobs

build-coq.8.11.2:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.11.2"
