image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"
  OCAML: "ocaml-variants.4.14.0+options ocaml-option-flambda"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  except:
  - triggers
  - schedules
  - api

## Build jobs

build-coq.8.20.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.0"
    DENY_WARNINGS: "1"

# Nightly job
trigger-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.20.0   coq-stdpp.dev git git+https://gitlab.mpi-sws.org/iris/stdpp.git#$STDPP_REV   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#$IRIS_REV"
  except:
  only:
  - triggers
  - schedules
  - api
